# Generated by Django 4.2.8 on 2025-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_topics',
            field=models.CharField(blank=True, default='', help_text='Comma-separated topics assigned by admin', max_length=500),
        ),
    ]
